- administration/scava-administration/src/app/layout/components/sidebar/sidebar.component.html
- administration/scava-administration/src/app/layout/layout-routing.module.ts
- administration/scava-administration/src/app/layout/project/components/configure-project/analysis-task-delete/analysis-task-delete-dialog.component.ts
- administration/scava-administration/src/app/layout/properties/properties-routing.module.ts
- administration/scava-administration/src/app/layout/properties/properties.component.html
- administration/scava-administration/src/app/layout/properties/properties.component.spec.ts
- administration/scava-administration/src/app/layout/properties/properties.component.ts
- administration/scava-administration/src/app/layout/properties/properties.delete/properties-delete-dialog.component.html
- administration/scava-administration/src/app/layout/properties/properties.delete/properties-delete-dialog.component.ts
- administration/scava-administration/src/app/layout/properties/properties.model.ts
- administration/scava-administration/src/app/layout/properties/properties.module.spec.ts
- administration/scava-administration/src/app/layout/properties/properties.module.ts
- administration/scava-administration/src/app/shared/services/properties-service/properties.service.spec.ts
- administration/scava-administration/src/app/shared/services/properties-service/properties.service.ts
- administration/scava-administration/src/app/shared/services/worker-service/list-worker.service.ts
- api-gateway/org.eclipse.scava.apigateway/application.properties
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/AnalysisDeleteTaskResource.java
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/ApiApplication.java
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/PlatformCreationPropertiesResource.java
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/PlatformDeletePropertiesResource.java
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/PlatformListPropertiesResource.java
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/PlatformPropertiesByKeyResource.java
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/PlatformUpdatePropertiesResource.java
Fixed / Improvement:
- add feat platform generic properties configuration managed into the administration dashboard webapp.
> Use case analysis

- administration/scava-administration/src/app/account/signup/signup.component.html
> fix error #65 signup-form-validation

- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/ProjectListResource.java
Remove hard-coding pagination params in projetcList ws
> Fixes scava issues

- web-dashboards/scava-metrics/panels/scava-project.json
- web-dashboards/scava-metrics/setindexpattern.py
This PR allows to set a default index pattern. It fixes #78
> [web-dashboards] Fix default index

- administration/scava-administration/src/app/layout/project/project-delete/project-delete-dialog.component.html
- administration/scava-administration/src/app/layout/project/project-delete/project-delete-dialog.component.ts
- administration/scava-administration/src/app/layout/project/project.component.html
- administration/scava-administration/src/app/layout/project/project.component.ts
- administration/scava-administration/src/app/layout/project/project.module.ts
- administration/scava-administration/src/app/shared/services/project-service/delete-project.service.ts
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/ApiApplication.java
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/ProjectDeleteResource.java
Fixes/Improvements:
* Provide the ability to delete a project from the admin web dashboard. This operation will:
* Delete the project from the scava database.
* Delete the project from the scava-analysis database including its analysis-tasks, its metric-executions.
* Delete the project's analysis database which contains the the analysis data calculated by the metric-providers
> Feat delete project from admin-dashboard #64 #103

- administration/scava-administration/src/app/layout/project/project.component.html
- metric-platform/platform/org.eclipse.scava.platform.osgi/config/log4j.properties
- metric-platform/platform/org.eclipse.scava.platform.osgi/src/org/eclipse/scava/platform/osgi/OssmeterApplication.java
- metric-platform/platform/org.eclipse.scava.platform.osgi/src/org/eclipse/scava/platform/osgi/analysis/MetricListExecutor.java
- metric-platform/platform/org.eclipse.scava.platform.osgi/src/org/eclipse/scava/platform/osgi/analysis/ProjectAnalyser.java
- metric-platform/platform/org.eclipse.scava.platform.osgi/src/org/eclipse/scava/platform/osgi/services/WorkerExecutor.java
- metric-platform/platform/org.eclipse.scava.platform/src/org/eclipse/scava/platform/AnalysisRepositoryManager.java
- metric-platform/platform/org.eclipse.scava.platform/src/org/eclipse/scava/platform/analysis/AnalysisSchedulingService.java
- metric-platform/platform/org.eclipse.scava.platform/src/org/eclipse/scava/platform/analysis/WorkerService.java
- metric-platform/platform/org.eclipse.scava.platform/src/org/eclipse/scava/platform/delta/ProjectDelta.java
- metric-platform/platform/org.eclipse.scava.platform/src/org/eclipse/scava/platform/logging/AnalysisProcessLogger.java
- metric-platform/platform/org.eclipse.scava.platform/src/org/eclipse/scava/platform/logging/AnalysisProcessLoggerFactory.java
Improvements:
* Provide an efficient logging system of the metric-platform to monitor the projects analysis process. It includes:
* The methods call and time execution traceability.
* The exception logs.
* A logs file will be generated associated to an analysis task by project. It will have the following naming format: ${Project_Name}:${Task_Name}-${Date_Task_Creation} ${Time_Task_Creation}
* The logs file will be saved on the following path:
${OS_Root}/scava/${Project_Name}/analysisLogs/
> Analysis process logging system

- administration/scava-administration/src/app/layout/project/components/create-project/create-project.component.html
- administration/scava-administration/src/app/layout/project/components/create-project/create-project.component.ts
- administration/scava-administration/src/app/layout/project/components/edit-project/edit-project.component.html
- metric-platform/platform/org.eclipse.scava.platform.client.api/META-INF/MANIFEST.MF
- metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/ProjectCreationResource.java
This PR provide support Jira Bug Tracking System on the admin-ui
> Add bts jira support #121

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
- web-dashboards/scava-metrics/panels/scava-dashboard.json
- web-dashboards/scava-metrics/panels/scava-factoids.json
- web-dashboards/scava-metrics/panels/scava-qm.json
- web-dashboards/scava-metrics/panels/scava-sentiment.json
- web-dashboards/scava-metrics/scava2es.py
This PR replaces https://github.com/crossminer/scava/pull/132 and https://github.com/crossminer/scava/pull/118 to simplify testing.
> [dashboards] Add dashboards 

- web-dashboards/scava-metrics/scava2es.py
This code sets the level of log messages related to fake data in order to reduce the size of the log.
> [scava2es] Set log message level to debug

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
This code updates the endpoints used to fetch the metrics data from SCAVA API.
> [perceval-scava] Update endpoints used

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
- web-dashboards/scava-metrics/scava2es.py
This PR allows to fetch and process the dependency data from the metric providers below:
- trans.rascal.dependency.maven.allMavenDependencies
- trans.rascal.dependency.maven.allOptionalMavenDependencies
- trans.rascal.dependency.osgi.allOSGiPackageDependencies
- trans.rascal.dependency.osgi.allOSGiBundleDependencies
Perceval has been enhanced with a new category to fetch dependency data. Each item contains the name of the `project`, the date when it was fetched (i.e., `datetime`, `updated`), project `meta` information, the `dependency` value and `id`, the `scava_metric_provider` from where the dependency was fetched, the dependency `type` (i.e., osgi or maven) and a `sub_type` which can be: `optional` for maven, and `package` or `bundle` for osgi. Each item is identified by a `uuid` …
> Extract and process dependency raw data

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
- web-dashboards/scava-metrics/scava2es.py
This PR enhances the scava perceval backend to fetch configuration dependencies (i.e., docker and puppet), which can be stored in a dedicated index, thus avoiding mixing with the development dependencies (i.e., maven and osgi.). Scava2es script has been modified accordingly.
> [dashboard] Handle configuration dependencies

- web-dashboards/scava-metrics/scava2es.py
This code allows to set the number of items uploaded per each bulk operation.
> [scava2es] Set bulk size for uploading items to ES

- web-dashboards/scava-metrics/scava2es.py
This code makes sure that the ES instance can process index creation/loading requests at the beginning of the scava2es operation. Thus, scava2es is blocked until the index is initialized.
> [scava2es] Handle ES instance not ready for index initialization

- metric-platform/metric-providers/org.eclipse.scava.metricprovider.trans.configuration.puppet.implementationantipatterns/pom.xml
Add pom.xml in Puppet Implementation Antipatterns Metric Provider
> Add pom.xml in Puppet Implementation Antipatterns Metric Provider

- metric-platform/metric-providers/org.eclipse.scava.metricprovider.trans.configuration.projects.relations/src/org/eclipse/scava/metricprovider/trans/configuration/projects/relations/ProjectsRelationsTransMetricProvider.java
Fix a bug that occurs because a wrong cast is made.
> Fix bug in ProjectsRelations Metric Provider

- web-dashboards/scava-metrics/panels/scava-sentiment-emotion.json
This code renames the sentiment dashboard to include also the concept of emotions.
> [dashboard] Rename sentiment dashboard

- web-dashboards/scava-metrics/panels/scava-sentiment-emotion.json
This code updates the title of the sentiment dashboard, which now
is scava-sentiment-emotion.
> [dashboard] Update title of sentiment dashboard

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
- web-dashboards/scava-metrics/scava2es.py
This PR includes allows to fetch data containing smells about puppet and docker configurations from the SCAVA API. The data is extracted from the following endpoints:
- 'org.eclipse.scava.metricprovider.trans.configuration.puppet.designsmells.PuppetDesignTransMetricProvider'
- 'org.eclipse.scava.metricprovider.trans.configuration.puppet.implementationsmells.PuppetImplementationTransMetricProvider'
- 'org.eclipse.scava.metricprovider.trans.configuration.docker.smells.DockerTransMetricProvider'
- 'org.eclipse.scava.metricprovider.trans.configuration.puppet.designantipatterns.PuppetDesignAntipatternTransMetricProvider'
- 'org.eclipse.scava.metricprovider.trans.configuration.puppet.implementationantipatterns.PuppetImplementationAntipatternTransMetricProvider'
The obtained data is then stored …
> Handle configuration smells data

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
- web-dashboards/scava-metrics/scava2es.py
This code allows to set the recommendation-url, thus allowing to fetch
recommendation data from different KB databases.
> [web-dashboards] Make recommendation-url tunable

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
- web-dashboards/scava-metrics/scava2es.py
This PR allows to fetch project relations data from the raw SCAVA API endpoint:
`org.eclipse.scava.metricprovider.trans.configuration.projects.relations.ProjectsRelationsTransMetricProvider` . The obtained data is then enriched and inserted in Kibana. 
The current enriched items contain the type of the relation (e.g., docker), thne name of the related
project, when the relation was calculated (`datetime`), plus project and meta project information. An example of enriched item is shown below:
```
"relation_type" : "docker",
"related_to" : "im",
"id" : "vim_im",
"updated" : "20190616",
"project" : "vim",
"datetime" : "2019-06-16T00:00:00+00:00",
"uuid" : "1fe3957fa267d89c86c3b1f5ca86fd28a40f7548",
"meta" : {
"top_projects" : [
"main"
]
}
```
> Handle project relations data

- web-dashboards/perceval-scava/perceval/backends/scava/sonarqube.py
- web-dashboards/scava-metrics/sonarqube2es.py
This code allows to process a list of sonarqube metrics defined by the user.
> [web-dashboards] Handle tunable list of sonarqube metrics

- web-dashboards/scava-metrics/sonarqube2es.py
This code allows to load components and mappings (the later used to replace the name of sonarqube projects) using a JSON The JSON content is as follows:
```
{
"_comment": "https://sonar.ow2.org/",
"component-mapping": {
"ASM:asm": "asm",
"fr.inria.gforge.spoon:spoon-core": "spoon",
"org.ow2.proactive:Scheduling": "scheduling",
"clif-legacy":"cliflegacy",
"org.ow2.sat4j:org.ow2.sat4j.pom":"sat4j",
"bonita-studio":"BonitaStudio",
"fr.inria.gforge.spoon:spoon-core":"spoon"
}
}
```
> [web-dashboards] Load sonarqube projects and mappings via remote JSON

- web-dashboards/perceval-scava/perceval/backends/scava/omm.py
- web-dashboards/scava-metrics/omm2es.py
This PR improves the code of `omm2es` by fixing minor bugs that were preventing the correct upload of the enriched items generated to Elasticsearch
> [scava-metrics] Allow omm2es to upload data to Elasticsearch

- web-dashboards/scava-metrics/scava2es.py
This code includes a new metric derived from Method Hiding Factor (Java) which consists in filtering out the values smaller than 0.10
> [scava2es] Add digested metric Method Hiding Factor (Java)

- web-dashboards/perceval-scava/perceval/backends/scava/scava.py
This code provides a fix to cope with a recent change in the format of the metrics concerning topics.
> [web-dashboards] Fix change in output format topics

- web-dashboards/scava-metrics/scava2es.py
This code removes the scava data from the ES items, thus
reducing the size of the indexes. Furthermore the metric
`documentation.readability.entries` is filtered out due to
a wrong format (it's not a linechart) which breaks the
scava2es importer process. Finally the metric
`Method Hiding Factor (Java)` is added again together with
the modified version `Method Hiding Factor (Java) GT 10`.
> [scava2es] Remove scava data from ES items

- knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/business/ISimilarityManager.java
- knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/business/SchedulerManager.java
- knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/business/impl/FOCUSSimilarityCalculator.java
- knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/business/impl/OssmeterImporter.java
- knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/business/impl/SimilarityManager.java
- knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/presentation/rest/ArtifactsRestController.java
- knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/presentation/rest/RecommenderRestController.java
A scheduled task has been added. It imports projects from the mpp. Metadata are updated If the project already exists.
> Importing project from the Metric provider platform to the KB
